run:
  go: '1.20'
  timeout: 5m
linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle
    - misspell
    - depguard

linters-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
  tagliatelle:
    case:
      use-field-name: false
      rules:
        yaml: snake
        json: snake
  depguard:
     list-type: 'denylist'
     packages-with-error-message:
       - 'github.com/pkg/errors': 'use stdlib instead'
