env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
  - go mod tidy
gomod:
  proxy: true
builds:
- main: ./cmd/nfpm
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
dockers:
  - image_templates:
      - 'goreleaser/nfpm:{{ .Tag }}-amd64'
      - 'ghcr.io/goreleaser/nfpm:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use_buildx: true
    binaries:
      - nfpm
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'goreleaser/nfpm:{{ .Tag }}-arm64v8'
      - 'ghcr.io/goreleaser/nfpm:{{ .Tag }}-arm64v8'
    dockerfile: Dockerfile
    use_buildx: true
    binaries:
      - nfpm
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64/v8"
    goarch: arm64
docker_manifests:
  - name_template: 'goreleaser/nfpm:{{ .Tag }}'
    image_templates:
      - 'goreleaser/nfpm:{{ .Tag }}-amd64'
      - 'goreleaser/nfpm:{{ .Tag }}-arm64v8'
  - name_template: 'ghcr.io/goreleaser/nfpm:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/goreleaser/nfpm:{{ .Tag }}-amd64'
      - 'ghcr.io/goreleaser/nfpm:{{ .Tag }}-arm64v8'
  - name_template: 'goreleaser/nfpm:latest'
    image_templates:
      - 'goreleaser/nfpm:{{ .Tag }}-amd64'
      - 'goreleaser/nfpm:{{ .Tag }}-arm64v8'
  - name_template: 'ghcr.io/goreleaser/nfpm:latest'
    image_templates:
      - 'ghcr.io/goreleaser/nfpm:{{ .Tag }}-amd64'
      - 'ghcr.io/goreleaser/nfpm:{{ .Tag }}-arm64v8'
changelog:
  filters:
    exclude:
      - Merge
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brews:
- tap:
    owner: goreleaser
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/goreleaser/nfpm
  description: nFPM is not FPM
  test: |
    system "#{bin}/nfpm -v"
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  https://github.com/goreleaser/nfpm
  description: nFPM is not FPM
  maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
  license: MIT
  vendor: GoReleaser
  formats:
  - apk
  - deb
  - rpm
scoop:
  bucket:
    owner: goreleaser
    name: scoop-bucket
  homepage:  https://goreleaser.com
  description: Deliver Go binaries as fast and easily as possible
  license: MIT
